- .env.example
- INSTALL.md
- server/config.js
- server/logsApi.js
- tests/end2end/createSubscriptionForm.spec.js
- tests/unit/config.spec.js
#11 Configurable Scalyr request.
New optional configuration parameter `SCALYR_BASE_FILTER` added. 
It is used to preselect log messages before finding consumers or producers of an event type.
This helps to adapt UI to different Scalyr setups.
Default value is the same.
`($serverHost=="nakadi") and ($logfile=="/var/log/application.log") and`
For staging, for example, it can be
`(($serverHost=="nakadi-staging") or ($serverHost=="nakadi-sandbox"))  and ($logfile=="/var/log/application.log") and`
> #11 Configurable scalyr request.

- client/Pages/EventTypeDetails/Messages.elm
- client/Pages/EventTypeDetails/Models.elm
- client/Pages/EventTypeDetails/PublishTab.elm
- client/Pages/EventTypeDetails/Update.elm
- client/Pages/EventTypeDetails/View.elm
- elm-package.json
- package-lock.json
- tests/mocks/data/error207.json
- tests/mocks/testNakadi.js
A new tab "Publish Event" added to the event type details page.
It allows the user to publish a batch of events to a selected event type.
It should help to test/debug consumers, test/debug event type schemas, manually fire processing workflows.
In case of server-side error, the error message shows the details.
> Publish events to event type

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Update.elm
- client/Pages/EventTypeCreate/View.elm
- tests/end2end/createEtForm.spec.js
#12 make AUDIENCE field required and with the blank option on the create/update Event type form.
The form also was a bit refactored to use semantic specific readable types instead of generic True/False
> #12 make AUDIENCE field required and with blank option

- client/Pages/EventTypeCreate/View.elm
As requested in #13 the message was changed on the create ET form for the cleanup strategy field.
Support link added.
> #13 Change the log compaction warning

- client/Constants.elm
- client/Helpers/Panel.elm
- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeDetails/Messages.elm
- client/Pages/EventTypeDetails/Models.elm
- client/Pages/EventTypeDetails/PublishTab.elm
- client/Pages/EventTypeDetails/QueryTab.elm
- client/Pages/EventTypeDetails/Update.elm
- client/Pages/EventTypeDetails/View.elm
- client/Pages/NotFound/View.elm
- client/assets/styles.css
- Refactor Event Publishing tab, make publish tab as independent sub-component of the event type details page.
- Add template with metadata (only for "business" ET fro now)
- Show publishing request status and hide "Success" message after 3s.
> #22 Fix some event publishing UX problems

- client/Pages/EventTypeCreate/Update.elm
- client/Pages/SubscriptionCreate/Update.elm
- client/Stores/Authorization.elm
- client/Update.elm
What: 
Set current user full access for created ET, Sub and Query.
The user can still remove themselves from access list or change permissions.
This feature is only for convenience. 
Why:
Often people forget to set them selfs as an admin of Event types, Subscriptions or Queries created by them in UI. It leads to manual work and distraction as people ask support to give them permissions for their entities.
> Set current user full access for created ET, Sub and Query

- client/Pages/EventTypeCreate/Query.elm
Do not allow users to choose the event type category for the output of a SQL query.
This is because the SQL query API currently always creates a business event type.
> Remove ability to choose event type category in query creation

- client/Pages/EventTypeCreate/Query.elm
Allow users to select category for output event type. Reverts the changes made in https://github.com/zalando-nakadi/nakadi-ui/pull/36/files.
Ticket Link: https://jira.zalando.net/browse/ARUHA-2154
> Allow users to select category for output event type

- client/Pages/EventTypeDetails/QueryTab.elm
- client/Stores/Query.elm
Queries no longer have a status. They are either active or completely
removed.
This PR removes the field from the model to make sure it works
correctly again with this incompatible change to Nakadi SQL API.
> Remove status field from query

- client/Pages/SubscriptionCreate/Models.elm
- client/Stores/Subscription.elm
Nakadi does now allow to change or omit "initial_cursors" field, so in case when the subscription was created with initial cursors the update(PUT) also requires this field. It was never needed in UI before so encoder/decoder for  "initial_cursors" was missing.
> #49 Fix Subscription update error

- client/Pages/EventTypeCreate/Update.elm
- client/Pages/SubscriptionCreate/Update.elm
- client/Stores/Authorization.elm
Do not modify ET and Subscription auth on update.
This change removes an automatic set of the current user name to auth section for an Event Type and Subscription updates.
This change also allows the user to remove all the auth configuration and send `"authentication": null` to the server.
> #61 Do not modify ET and Subscription auth on update

- server/App.js
Fix `Payload Too Large` error by setting the limit to match Nakadi limit https://nakadi-faq.docs.zalando.net/#what-is-the-maximum-batch-size-nakadi-could-send-out
> #72 Fix Payload Too Large error

- client/Helpers/AccessEditor.elm
- client/Pages/EventTypeDetails/Help.elm
Remove wildcard admin checkbox. Also, if there is already `admin` with `*` there for an event type, the checkbox is still visible.
> Remove checkbox for admins for all

- .codecov.yml
- .gitignore
- .travis.yml
- CONTRIBUTING.md
- INSTALL.md
- package-lock.json
- package.json
- tests/end2end/createEtForm.spec.js
- tests/end2end/createSubscriptionForm.spec.js
- tests/end2end/helpers/browser.js
- tests/end2end/helpers/session.js
- tests/end2end/resetSubscriptionOffsetForm.spec.js
- tests/end2end/search.spec.js
- tests/mocks/data/appConf.json
All tests generate test coverage reports. We now publishing them to "codecov.io" for analyzing (if som one needs it) but without annoying PR comments.
The test now uses a prebuilt version of UI.
The test was failing randomly, depending on the host speed. I found that is dev mode every new test dynamically rebuilds the whole UI. It is because of dev mode assumes hot module reloading if underlying code file changes.
So to speed up tests and make them more reliable we test built production version, so it builds once and then used in all tests. The runs twice as fast minimum.
> Add and publish test coverage reports

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Update.elm
- client/Pages/EventTypeCreate/View.elm
- client/Pages/EventTypeDetails/Help.elm
- client/Pages/EventTypeDetails/View.elm
- client/Stores/EventType.elm
Add support for field `event_owner_selector` with fields: `type`, `name` and `value`.
(See: https://github.com/zalando/nakadi/pull/1145/files for more details)
It should be possible to update the field, create an event type with the field and view the field in the event type definition.
> Add support for event_owner_selector

- client/Pages/EventTypeDetails/Models.elm
- client/Pages/EventTypeDetails/Update.elm
- client/Pages/EventTypeDetails/View.elm
Tracking publishing has been disabled due to volume
reasons for some time. This stops the tab showing up
in the view.
> Removes publisher tab from console view.

- INSTALL.md
- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Update.elm
- client/Pages/EventTypeCreate/View.elm
- package-lock.json
Users often change schemas without fully understading the consequences. This leads to multiple incidents and increased support effort in order to work around and amend such mistakes.
We consider that displaying a message asking for confirmation and alerting users to the potentially dangerous actions they are about to perform could have a positive impact.
The dialog is only shown when there are changes in the schema. Otherwise it continues to work as before.
> Display a confirmation dialog when updating schemas

- client/Pages/EventTypeCreate/Update.elm
When introducing the alert message, a new operation was added UpdateConfirm, which causes the warning message to be displayed and the form to be hidden.
Once the form is submitted, if the server answers with an error, 422 in case of invalid change, the error message would not be displayed to the user, as this message is only displayed in the `Update` operation and not in the `UpdateConfirm`.
This change switched back the state of the page to `Update` after confirming the dialog and submitting it. Then the message is again correctly displayed at the bottom of the page as before.
> Correctly display error messages returned by the server

- client/Pages/EventTypeCreate/Update.elm
Even though automatic formatting is turned on by default, this specific case is not covered and caused the pipeline to fail.
> Fix formatting

- client/Pages/EventTypeDetails/View.elm
When clicking the monitoring link for an event type that is the output
of a Nakadi SQL, users were redirected to a dashboard that wasn't
displaying any data. That's because for such event types a different
dashboard would be better suited, as the source of data has to be a
different one (not Nakadi but Nakadi SQL).
> Nakadi SQL query output event type monitoring link

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeDetails/Help.elm
- client/Stores/EventType.elm
When creating a new query, Nakadi SQL would process the entire backlog
of events sitting in the input event types. This lead to a spike in
load and the production of potentially a lot of events.
The decision to process all the events was made when we only had
queries for which this is the only sensible choice, namely FULL OUTER
JOINs.
In a full outer join, not having the complete state of the input event
types makes little sense.
But since then, a lot has changed and currently the most common type
of query are stateless queries, meaning filters and projections. For a
significant amount of users, producing events retroactively is not the
expected behaviour and is the most cost inneficient, thus this field
is introduced with default to 'end'.
There is a chance users might pick 'end' without …
> Add read_from option to query creation

- client/Pages/EventTypeCreate/Query.elm
The field was passed in the wrong place and as the API is lenient, it
accepted the request without informing the calling application that it
was passing something in the wrong place.
I think we should review this lenience as it allows for typos to go undetected.
> Read from is not a property of the output event type

- client/Pages/EventTypeCreate/Models.elm
This was causing an issue when creating queries that would force the
user to select the `read_from` in the form even though it was already
displaying as selected. That's because of how forms work in this app,
they are not extracted from a readl html form.
> Missing default value

- client/Pages/EventTypeCreate/Update.elm
Allow number after dots in event type name (same as https://nakadi.io/manual.html#definition_EventType*name)
> Allow numbers after dots in event type name

- client/Pages/EventTypeCreate/View.elm
Add option to change cleanup policy from `delete` to `compact_and_delete` while updating an event type. 
Related Nakadi change: https://github.com/zalando/nakadi/pull/1235
> Allow cleanup policy change for delete to compact_delete

- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeDetails/Help.elm
Change the example for `partition_compaction_key_field` to include the <payload> table alias. (the table alias in example query is `payload`)
> Change the documentation example for partition_compaction_key_field

- client/Pages/EventTypeDetails/QueryTab.elm
- client/Stores/Query.elm
> Adding status to query

- server/config.js
- tests/unit/config.spec.js
> Set secure flag for the session cookie

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/SubscriptionCreate/Models.elm
- tests/end2end/createEtForm.spec.js
- tests/end2end/createSubscriptionForm.spec.js
There is no meaning in having default value that users have to constantly override.
> Change default owning application for event type, query create to an empty value

- client/Pages/SubscriptionDetails/View.elm
Sometimes it's helpful to have a quick way to check it.
> Show partitions count on subscription stats page
