- Dockerfile
- README.md
- docker-compose.yml
- package-lock.json
- package.json
- server/nakadiApi.js
- server/nullPassportStrategy.js
- Dockerfile and docker-compose added as requested in #4 
-  `nullPassportStrategy.js` added to bypass authentication,
- Some workaround was required to deal with Nakadi issue https://github.com/zalando/nakadi/issues/792 
- package.json changed and  package-lock.json added to reduce warnings on docker image compiling.
> #4 Add Dockerfile and docker-compose

- CHANGELOG.md
- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Update.elm
- client/Pages/EventTypeCreate/View.elm
- client/Pages/EventTypeDetails/EffectiveSchema.elm
- client/Pages/EventTypeDetails/Help.elm
- client/Pages/EventTypeDetails/View.elm
- client/Stores/EventType.elm
- client/Tests/EventTypeStore.elm
- server/validation/index.js
- tests/api/validationApi.spec.js
- tests/mocks/testNakadi.js
- tests/unit/validationRules.spec.js
Added audience and cleanup_policy fields.
Added validation check to encourage usage of "audience" field.
> #7 Add audience and cleanup_policy fields

- CHANGELOG.md
- elm-package.json
- package.json
1. Changelog update
2. Version bump to 1.0.0
> Release v1.0.0

- README.md
Add a link to the related talk to the readme
> Add a link to the related talk to the readme

- client/Helpers/AccessEditor.elm
#17 Add remove item button on access control
> #17 Add remove item button on access control

- client/Pages/EventTypeCreate/Update.elm
What:
Fix Form validation
Why:
Event type Update form was not properly validating "owning_application" and "audience" fields.
Create SQL Query form was not validated existing of SQL query
> #26 Fix validation on update and create query

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeDetails/Help.elm
Add cleanup policy field for output event type.
> Add mandatory field for cleanup policy

- client/Pages/EventTypeCreate/Models.elm
Use double quotes for the example query in the sql editor
> Use double-quotes for example query

- CONTRIBUTING.md
- INSTALL.md
- client/Native/Ace.js
- client/Native/Browser.js
- client/Native/FileReader.js
- client/Native/LocalStorage.js
- elm-package.json
- package.json
Update repository link after transfer to zalando-nakadi
> Update repository link after transfer to zalando-nakadi

- client/Pages/SubscriptionDetails/View.elm
This has been annoying me for quite some time.
> Fix typo in Subscription details

- client/Stores/SubscriptionStats.elm
#57 Fix subscription stats decoder.
Making some fields optional
> #57 Fix subscription stats decoder

- client/Pages/EventTypeDetails/View.elm
#60 Change wording for consumers on event type page
> #60 Change wording for consumers on event type page

- client/Pages/EventTypeDetails/Help.elm
- client/Pages/EventTypeDetails/View.elm
- client/Pages/Partition/View.elm
#42 Add help popup for total in compacted ET
> #42 Add help popup for total in compacted ET

- client/Pages/EventTypeCreate/Messages.elm
- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeCreate/Update.elm
SQL Query validation button added.
Valid
Error
> #45 Add SQL Query Validation button

- client/Pages/Partition/View.elm
Fix swapped icons on inspect events pager
> #70 Fix swapped icons on inspect events pager

- .travis.yml
- package-lock.json
- package.json
The goal is to fully test Nakadi UI in isolation, build and publish docker that can be used as a base layer in the real deployment.
> Run full e2e tests on TravisCI and build docker

- client/assets/styles.css
Fix for layout problem #35
Just the event list height adjustment.
> Fix layout problem #35

- delivery.yaml
Use the Environment variable to build and publish the docker image.
> Fix docker push

- delivery.yaml
- tests/end2end/resetSubscriptionOffsetForm.spec.js
> Fix docker push 2

- INSTALL.md
While setting up this project for local development, I found the
following hints useful to speed up the process.
> Extend documentation to easy the setup for new developers

- client/Pages/EventTypeDetails/Help.elm
- client/Pages/EventTypeDetails/Update.elm
- client/Pages/EventTypeDetails/View.elm
> Adding list of consuming queries to consumers tab

- client/Pages/EventTypeCreate/View.elm
> Allow retention time 1 day

- package-lock.json
- package.json
Some dependencies were updated to be able to pass tests.
> Partially update dependencies

- client/Pages/EventTypeCreate/Models.elm
- client/Pages/EventTypeCreate/View.elm
- client/User/Commands.elm
- client/User/Models.elm
- server/config.js
- tests/unit/config.spec.js
Aruha 2785 Allow to reconfigure default retention time and values to put in retention time
> Aruha 2785 Allow to reconfigure default retention time and values to put in retention time

- client/Pages/EventTypeCreate/Models.elm
- tests/mocks/testNakadi.js
Temporary change default retention time
> Change default retention time to 1 day

- .env.example
- Dockerfile
- client/Pages/EventTypeCreate/Update.elm
- client/Pages/EventTypeCreate/View.elm
- client/User/Commands.elm
- client/User/Models.elm
- server/config.js
- tests/unit/config.spec.js
* have a 'cancel' button. Currently to cancel you have to click on the x sign
* have a link to the documentation for what changes are allowed in each compatibility mode
* do not have the pop up if compatibility mode is 'undefined', since there would be no schema changes that can't be rolled back then
> Improvements to schema change dialog

- client/Pages/EventTypeCreate/Query.elm
- client/Pages/EventTypeCreate/View.elm
- client/Pages/EventTypeDetails/Help.elm
- client/Stores/EventType.elm
Add commit_and_delete cleanup policy for EventType, Query
As part of this extension to nakadi: https://github.com/zalando/nakadi/pull/1219, introduce additional cleanup policy to the Nakadi UI.
> Add commit_and_delete cleanup policy for EventType, Query

- client/Pages/EventTypeCreate/Models.elm
> Elm format

- client/Pages/EventTypeCreate/View.elm
This is linked to https://github.com/zalando/nakadi/pull/1226
> Allow to change the compatibility mode in any direction

- package-lock.json
- package.json
The build stopped working without any changes in code or libraries.
Comparing the logs from prior successful builds and their
corresponding failing build (same commit) I could notice that the
underlying chromium-browser package installed in ubuntu changed form
version 81.0.* to 84.0.*. My guess is that the driver used is
incompatible with this new version so instead of forcefully
downgrading chromium brower I'm trying to upgrade the driver.
> Attempt to fix broken build

- .travis.yml
- Dockerfile
- package-lock.json
- package.json
> Update base image for nakadi-ui

- package-lock.json
- package.json
> Upgrade chromedriver

- client/Pages/EventTypeCreate/View.elm
The guidelines were updated and there is a new MUST rule for the data category.
> Update API guidelines reference

- client/Pages/EventTypeCreate/View.elm
- package-lock.json
- package.json
- server/App.js
> Respond with X-Frame-Option: Deny for all requests

- delivery.yaml
- server/logger.js
> Try harder not to log sensitive information

- client/Helpers/AccessEditor.elm
Changing position of team among team, user & service
> Changing position of team among team, user & service
